openapi: "3.0.1"
info:
  title: Messages Service API
  description: Messages Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /bottlebox/{label}:
    get:
      tags: [ Messages ]
      description: Get the list of the requested messages by the user 
      operationId: mib.resources.messages.get_bottlebox
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequesterID'
      parameters:  
        - name: label
          description: Messages type
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return user
        400:
          description: Bad request
        404:
          description: User not found
        default:
          description: An error occured while retrieving the list of users

  /messages/received/{message_id}:
    get:
      tags: [ Messages ]
      description: Get details of a received message
      operationId: mib.resources.messages.get_received_message
      parameters:
        - name: message_id
          description: Message id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequesterID'
      responses:
        200:
          description: Return message
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Message not found
        default:
          description: An error occured while retrieving the message
  
  /messages/drafts/{message_id}:
    get:
      tags: [ Messages ]
      description: Get details of a draft message
      operationId: mib.resources.messages.get_draft_message
      parameters:
        - name: message_id
          description: Message id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequesterID'
      responses:
        200:
          description: Return message
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Message not found
        default:
          description: An error occured while retrieving the message
   
  /messages/pending/{message_id}:
    get:
      tags: [ Messages ]
      description: Get details of a pending message
      operationId: mib.resources.messages.get_pending_message
      parameters:
        - name: message_id
          description: Message id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequesterID'
      responses:
        200:
          description: Return message
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Message not found
        default:
          description: An error occured while retrieving the message
   
  /messages/delivered/{message_id}:
    get:
      tags: [ Messages ]
      description: Get details of a delivered message
      operationId: mib.resources.messages.get_delivered_message
      parameters:
        - name: message_id
          description: Message id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequesterID'
      responses:
        200:
          description: Return message
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Message not found
        default:
          description: An error occured while retrieving the message

  /hide:
    delete:
      tags: [ Messages ]
      description: Get message details
      operationId: mib.resources.messages.hide_message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequestBody'
      responses:
        200:
          description: Delete message for the user recipient
        403:
          description: Forbidden
        default:
          description: An error occured while retrieving the message

components:
  schemas:
    RequesterID:
      required:
        - requester_id
      type: object
      properties:
        requester_id:
          type: integer
          format: int64
          description: user ID
          example: 1

    MessageRequestBody:
      required:
        - requester_id
        - message_id
      type: object
      properties:
        requester_id:
          type: integer
          format: int64
          description: user ID
          example: 1
        message_id:
          type: integer
          format: int64
          description: message ID
          example: 12