openapi: "3.0.1"
info:
  title: Messages Service API
  description: Messages Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /bottlebox/{user_id}/{label}:
    get:
      tags: [ Messages ]
      description: Get the list of the requested messages by the user 
      operationId: mib.resources.messages.get_bottlebox
      parameters:
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: label
          description: Messages type
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return user
        400:
          description: Bad request
        404:
          description: User not found
        default:
          description: An error occured while retrieving the list of users

  /messages/{user_id}/{label}/{message_id}:
    get:
      tags: [ Messages ]
      description: Get message details
      operationId: mib.resources.messages.get_message
      parameters:
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: label
          description: Message type
          in: path
          required: true
          schema:
            type: string
        - name: message_id
          description: Message id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return message
        400:
          description: Bad request
        403:
          description: Forbidden
        404:
          description: Message not found
        default:
          description: An error occured while retrieving the message
    
  /hide/{message_id}/{user_id}:
    get:
      tags: [ Messages ]
      description: Get message details
      operationId: mib.resources.messages.hide_message
      parameters:
        - name: message_id
          description: Message id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Return message
        403:
          description: Forbidden
        default:
          description: An error occured while retrieving the message