openapi: "3.0.1"
info:
  title: Messages Service API
  description: Messages Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /bottlebox/{user_id}/{label}:
    get:
      tags: [ Messages ]
      description: Get the list of the requested messages by the user 
      operationId: mib.resources.messages.get_bottlebox
      parameters:
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: label
          description: Messages type
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return user
        400:
          description: Bad request
        404:
          description: User not found
        default:
          description: An error occured while retrieving the list of users
